backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Shows"
    name: "shows"
    format: "json"
    file: "content/shows/shows.json"
    fields:
      - label: "Shows"
        name: "showsArray"
        widget: "list"
        summary: "{{fields.date}} — {{fields.city}}"
        fields:
          - {label: "Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY", format: "DD.MM.YYYY", timeFormat: false}
          - {label: "City", name: "city", widget: "string"}
          - {label: "Venue", name: "place", widget: "string"}
          - {label: "Button text", name: "linkName", widget: "string", default: "More info"}
          - {label: "Link URL", name: "linkURL", widget: "string", required: false}